apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: istio-system
spec:
  secretName: "${domain}-tls"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "${domain}"
  dnsNames:
    - "${domain}"