apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  namespace: argocd
  name: argocd-image-updater-config
data:
  git.user: "Update Bot"
  git.email: vietanhduong@users.noreply.github.com 
  registries.conf: | 
    registries:
    - name: Docker Hub
      api_url: https://registry-1.docker.io
      ping: yes
      defaultns: library
  git.commit-message-template: |
    Automatic update image of {{ .AppName }}

    {{ range .AppChanges -}}
    Updates image {{ .Image }} tag '{{ .OldTag }}' to '{{ .NewTag }}'
    {{ end -}}
  
    