apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: resume-cert
  namespace: istio-system
spec:
  secretName: "resume.anhdv.dev-tls"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "resume.anhdv.dev"
  dnsNames:
    - "resume.anhdv.dev"