apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  namespace: resume
  name: resume-gw
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http-resume
        protocol: HTTP
      hosts:
        - resume.anhdv.dev
    - port:
        number: 443
        name: https-resume
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: "resume.anhdv.dev-tls"
      hosts:
        - resume.anhdv.dev
